#+title: frames
#+roam_alias: framing
#+spotify_href: spotify:track:2MYPFXScWdR3PQihBQxu7x

[[file:marrs_levels.org][Marr's Levels]] framework:
- computational: Goals
- algorithmic: [[file:frames.org][frames]]
- implementation: [[file:current.org][current things I'm doing]]


Man, this one is gonna get so cool once I have transclusion. can be like, frames galore!~

Warning: this document is gonna get big. In order to avoid the "storing acorns for the winter effect" as I call it, we have to cross-list important frames and *link* stuff.

This note contains both meta-information that informs my conception of frames, as well as examples of powerful frames themselves.

Some of these are sort of procedures/algorithms. Like search and storing config files.

I want to be able to seamlessy activate different mental frames, and apply them to the game that I'm currently playing.

I definitely have a note /full/ of stuff like this somewhere in the constellation.

* Meta-information on frames
  
There is no pure hierarchy of things. So I think.

But frames establish a structure. Maybe. They're a constraint on our patterns of thought.

Pictures = mental keys, unlock what’s already inside our heads. 

So what is intelligence?

I think that ultimately a sea of non-concreteness is no way to live a life. You need something concrete, something organizing. A religion, a philosophy, a fundamental axiom, something that you hold sacred. But.... it should not be too concrete of a sacred item. And it should be mutable. 

I need direction in life. That would realize my potential.

Design thinking—say the first thing in your mind, then iterate.

** What is a frame?
*** An if-then rule
*** A mindset/mind backdrop
    Like, either something that sort of leaks subconsciously and influences eveything else, or something that I consciously put into place. Which leads into the next bullet...
*** A set of constraints
*** An idea space?
** External thoughts on framing
*** Kahneman/priming, experimental operationalizations, visakanv thinking/infinite games, Literal Banana against scientific operationalization (restricting frame,)
*** Minsky against math education as a skimpily-connected frame,
*** Hofstadter on [[file:analogy.org][analogy]]/concepts, tetris effect
    There is so, so much to unpack here.
*** Central tenets of framing ([[http://sadfor.us/wp-content/uploads/2017/09/Dont-Think-of-an-Elephant.pdf][Lakoff 2004]])
**** a. Every word has a frame.
**** b. Negating a frame evokes that frame. (cf. Hypothesis N)
**** c. Evoking a frame reenforces that frame.
** Operations on frames
*** Stretching frames
frames like being stretched in certain directions. Some directions fit like a glove. However, some directions...it just doesn't work out. For example -- "organize everything" according to some organizational philosophy...it's awesome for physical possessions, pretty good for digital ones too. But how about mental possessions? that's a little bit sketch.
*** Re-framing
Like...modify the frame.
Example: [[https://www.quantamagazine.org/the-useless-perspective-that-transformed-mathematics-20200609/][representation theory]].
* Bad frames
** Perfectionism
   Trying to optimize things that are ultimately meaningless, or that are hindering progress on what's /actually/ important.
** Toxic Comparison/Competition
   Like, the kind that makes you feel bad inside. 
** "I need to figure everything out now!!"
   Probably related to perfectionism in some base way. Trying to come to an analytical solution when it'd be way easier to implement an iterative one.
* [[http://donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system/][Leverage points: Places to Intervene in a System]]
  Lots of stuff about systems thinking in this one.
** PLACES TO INTERVENE IN A SYSTEM
(in increasing order of effectiveness)
*** Constants, parameters, numbers (such as subsidies, taxes, standards).
*** The sizes of buffers and other stabilizing stocks, relative to their flows.
*** The structure of material stocks and flows (such as transport networks, population age structures).
*** The lengths of delays, relative to the rate of system change.
*** The strength of negative feedback loops, relative to the impacts they are trying to correct against.
*** The gain around driving positive feedback loops.
*** The structure of information flows (who does and does not have access to information).
*** The rules of the system (such as incentives, punishments, constraints).
*** The power to add, change, evolve, or self-organize system structure.
*** The goals of the system.
*** The mindset or paradigm out of which the system — its goals, structure, rules, delays, parameters — arises.
*** The power to transcend paradigms.
* mastering the most basic skills and moving up
Master your tools. Vim is a strong metonymy for thinking about this example.
* noticing inefficiencies
* [[https://twitter.com/david_perell/status/1277088921097125888?s=21][treat your craft like an athlete treats their sport.]]
being prolific is important, incorporating high-signal feedback is also important. World-class athletes do both. So...what's my training regimen for what I wanna do?

This applies quite directly for workout and diet. It's a closed system.

@visakanv is right. build 100 things.
* build 100 things. / Be prolific (Picasso, @visakanv, etc.).
* /mise en place/
Set up the kitchen before cooking.
* Sometimes, when there are explosively many choices, just take the greedy option and
* Changing the settings
like in this thought (link is slow -- hmm...how could I improve this?)
* [[file:marrs_levels.org][Marr's levels]]
* structure as a constraint that leads to creativity.
  Like, it prevents you from spending too much time in the "config layer." Spend more time in the execution layer. But the perennial question is, "how much structure is too much structure?"
* Constraints => creativity
:PROPERTIES:
:ID:       afa561a8-e884-4a81-be70-f580dd72730f
:END:
* (avoid) competitive mindset
* Subtree frame vs. separate page frame
In the context of zettelkasten. These should be interchangeable, imo. (Yet another argument for a graph database backend 😅)
* Constantly staying in motion. Embracing change.
* you are what you eat.
* Repeatedly asking why. Get to the root.
* Light, playful frame.
* Constraints
* Keep It Simple Stupid (KISS)
Related to the idea of constraints supporting creativity--dead simple things, done /again and again/ are extremely powerful.
* Alexander technique
* Start simple and workable, and then unfold to something more complex.
  By induction, if you can progress from complexity k to k + 1, you
  can progress infinitely.
  
  Over time, I've gotten to know the amazing beast that is org mode.
  It is astounding how much you can do—but perhaps even more
  impressive is that you can start doing it on the first day. You can
  learn in 5 minutes how to create headlines, expand and collapse
  nodes, write text, etc. That is not hard.
  
  This, I feel, should be part of my life philosophy. Wanna start a
  self-reflective practice? Make it extremely, dead, simple at first.
  Make it solid. Then, gradually, you can build from there. But you
  need that foundation to be laid down first, otherwise things are all
  like the kids who took caffeine or steroids...stunted growth, or
  premature experience.
  
  Simple life philosophy. Simple running routine. Simple
  self-reflection routine. To start out with.
f Simulate having a conversation with someone.
  This works shockingly well in sort of being rational about things and hashing out points. Like imagine with Ian, or Chris, or someone very level-headed. Or simulate Sid for certain things. Or visakanv. Imagine DMing him with your problem.
* Practice Time vs. Performance Time.
:PROPERTIES:
:ID:       5c10a46c-9a85-4821-b6a8-3afffce72726
:END:
* While holding one frame, respect other (even contradicting) frames.
* Noticing assumptions and questioning them.
Assumptions, in my view, are synonymous with constraints. Powerful if you have a good set, but they should be dynamic.
* learn from the masters.
:PROPERTIES:
:ID:       6f220af9-0d79-4557-b900-085b7551dd6b
:END:
* Build your ideas.
* Nuking everything and starting over.
* [[http://www.paulgraham.com/head.html][Holding a program in one's head]]
Ooooh I really like this PG article. This, but generalized to any procedure/[[file:frames.org][frame]]/etc.
* Have you tried playing with a toy example?
  If you're struggling to understand something, *examples help*.
* Lightness / playfulness / lightness / playfulness / lightness / playfulness
* creative destruction
rewriting a program, for example
* Wayfinding => Mastery
** 1. Seek Sense-making tools like [[https://www.quantamagazine.org/the-map-of-mathematics-20200213/][map of mathematics]]
** 2. Start by mastering one node on the map, then move on to something else
** 3. Mastery?? [unfinished]
* You will die someday.
* Have good form / fundamentals
** For example: Typing, exercise
** [[https://twitter.com/visakanv/status/1029925579552739328?s=20][visakanv on good form in relationships]]
* [[file:decomposition.org][decomposition]]
* Going back to the formal definitions.
* Build a solid foundation, and then work from there.
* Just kinda start building vague associations and everything works out (knowledge graph)
* Taking the patterns you've seen so far, and generalizing them.
This is why everyone's particulars influence their worldview so much--they pattern-match, and because of our leaky, non-compartmentalized brains, they generalize. The model's usefulness can be shaky tho, sometimes we're observing truly general patterns, but sometimes we're just observing patterns that are specific to our slice of reality. Experience and worldview are deeply intertwined.
* debugging frame
* storing everything as "config files" for my life
  (dotfiles repo contains...everything?? my workout config, my posture config, my relationship configs, etc.)
* What is the actual meaningful *content*?
* Maximalism, minimalism
* Mindfulness/I-mode
  being able to step out when you've gone down an unproductive/too deep into the task tree. Effective backtracking.
* Sense of wonder at the way the world is
* Transmuting one type of "energy" to another
Like...pent-up frustrations into a stream of focused productivity. Wielding it instead of letting it drive me insane.
* Time
** [[https://www.ribbonfarm.com/2014/05/10/two-examples-of-narrative-time/][Expanding narrative time]]
* Life/habits as subroutines to be executed
* What's the point? 
  (Hierarchy of "why"s that end in ... long-term Goals? biological base desires? The stochastic nature of the universe?)
* peoplewatching through different lenses.
** Sonder - everyone else's existences are just as complex.
** Interactions - what information's being exchanged?
** sexual tension
** Interactions across race/gender/etc.
* Sensory deprivation => resensitization
* What are my "labels" that I'm training on? What is my training data?
  Like, it's all about having good supervision. this relates back to Tell said "track your macros - what's measured gets managed." You need to know the truth.
* *Search* as a tool to create things
* Good, old-fashioned hard work.
MJ worked his ass off and became the best basketball player known to man. Of course, you need talent and luck. He had those too. But you also need grueling, hard work to get to the top. Solid Habits.
* Actively try to fail. Put yourself in the path of failure.
:PROPERTIES:
:ID:       74802074-7706-4d39-939c-5d501ae21bb4
:END:
* 100 blocks per day. 10 minutes per block.
* Staying stateless.
