#+title: PSYCH 70: Social Psychology

* Introduction
Think about a time you were happy / a time you were sad-- were other people involved? We often experience emotions as a result of someone else.

** Social psychology is not new.
Philosophers have been intuitively (if not quite scientifically) thinking about these ideas for centuries!
#+begin_quote
"Anybody can become angry - that is easy, but to be angry with the right person and to the right degree and at the right time and for the right purpose, and in the right way - that is not within everybody's power and is not easy." - Aristotle
#+end_quote
** Social psychology is not (always) intuitive.
Example: [[https://rady.ucsd.edu/faculty/directory/gneezy/pub/docs/fine.pdf][introducing a fine]] for late-picker-uppers of kids at daycare actually /increases/ the number of late pick-ups. Explanation? The /motivation/ shifted from intrinsic to extrinsic.
** What is social psychology?
About understanding the "causal architecture" of the society that we're embedded in.

Three parts of the class: social cognition, interpersonal processes, everyday life.
*** Levels of organization:
Societies <=> *Groups* <=> *Individual* <=> *Mind* <=> Neurons/Genes/Hormones
^social psych is focused on the middle three levels.
* [[file:20210704202541-cognitive_biases.org][Cognitive Biases]]: self-serving biases.
** Motivated reasoning
/Motivated reasoning/ is our tendency to come to conclusions that make us feel good.

We don't like to admit when we're wrong! (Nor our sports heroes, family, political candidates, etc.)

Group affiliation: "We crushed them!" when your team wins vs. "They were terrible" when your team loses.

Above-average effect: people believe they are above average in valued domains (lol.) BUT in other domains that are seen as really hard (e.g. juggling or living past 100,) we see the below-average effect. The reason: we "anchor" to our initial estimate. E.g. for living to 100, we initially think it's very unlikely, then adjust the estimate upward as we get evidence.

Dunning-Kruger Effect: Correlation between lower skills and greater Above-Average Effect. In other words, correlation between cognitive and metacognitive skills. (Also, those with the most skills underestimate a little!)
** Why do we have these biases?
One answer: self-esteem. (But why do we need self-esteem, evolutionarily?)
Another answer: overconfidence gives social benefits?
** ...is there another way?
Hubristic pride = arrogant/conceited.
Authentic pride = confident, high self-esteem.
* Person Perception
/Should I date this person? Is this person guilty? How competent is this person?/

*Person perception* is forming impressions about other people.
** Thin Slicing
People can make predictive judgments "instantly" -- predicting future success, marriage success, sales performance, sexual orientation, etc. (Cue /Blink/ by Malcolm Gladwell, lol.)

Women can predict hetero/homosexual at higher rates when ovulating

These "thin slice" judgments can be surprisingly predictive, but also biased.

*** Why?
There is evolutionary value in swiftly identifying potential threats, mates, and leaders.
** Universal Dimensions of Social Cognition: Warmth and Competence
** Oh yeah, there's also the whole triangle and circe thing -- we immediately make judgments about what they're doing.
(But she should've mentioned that autistic people don't see this the same way)
** Confirmation bias:
Tendency to want to verify our pre-existing beliefs.
** Pygmalion Effect:
kids whose teachers thought the kids were "late bloomers" -- it actually came true.

Side note: whoa. Intuitively I feel like (and I'm of course enjoying that sweet confirmation bias) but it confirms my intuitions -- in cases where I've set high, clear expectations for myself, I've achieved them.
** [[file:20210627180445-self_fulfilling_prophecy.org][Self-fulfilling prophecy]]
You have expectations about someone => you behave accordingly towards them => they behave just how you expected => reinforces your expectations...

This seems like a kind of [[file:20210626152258-positive_feedback_loop.org][positive feedback loop]] that can either go really well, or really badly. Parents have a huge role in establishing expectations for their children. (As a first-born, I know this firsthand 😅)
* [[file:20210704202541-cognitive_biases.org][Cognitive Biases]]: cognitive dissonance theory
Cognitive Dissonance Theory:
- cognitive dissonance :: holding apparently incompatible / logically inconsistent thoughts about the world.
** How to resolve dissonance between A and B?
You can *disregard* one.
You can *change* your belief in one.
You can *distort* one.
You can *add* C that resolves the conflict.

Which one to choose? Will probably go with the path of least resistance.

Chicago doomsday cult didn't see doomsday => rationalized by saying that the Guardians had stopped the flood

1755 Lisbon earthquake => threatened belief in God and a just world.
** Is dissonance reduction good?
Good: it allows you to streamline cognition.
Bad: it loses the inherent complexity / ambiguity in the world.

#+begin_quote
A foolish consistency is the hobgoblin of little minds. - Ralph Waldo Emerson
#+end_quote
** Motivated reasoning is a key element in cognitive dissonance.
Severity of initiation: we have a deep-seated belief that we're not gullible etc. Motivated reasoning leads us to believe that the task was actually interesting, rather than that we're just gullible.
** Behavior precedes thought
Spreading of alternatives: we post-hoc try to "justify" our decisions in life to ourselves.

Cognitive Behavioral Therapy: change behaviors in people's lives to change their psychology positively.

Don't /think/ like you're the person you want to be, /act/ the way you want to be and become that person.
* TODO [[file:20210704202541-cognitive_biases.org][Cognitive Biases]]: attribution
* [[file:20210716222804-norms.org][Norms]]
- Norms :: Social "rules" that determine appropriate, acceptable behavior in a certain context.
- Descriptive norms :: common patterns of behavior
- Injunctive norms :: patterns of behavior that are commonly approved of / evaluated positively


Injunctive (top) vs Descriptive? (left)
|                  | Descriptive - Yes                       | Descriptive - No             |
|------------------+-----------------------------------------+------------------------------|
| /                | <                                       | <                            |
| *Injunctive - Yes* | - driving on the right side of the road | - sharing cable accts        |
|                  | - taking turns in conversation          | - culturally divisive issues |
|                  | - standing in line                      | - solar panels               |
|------------------+-----------------------------------------+------------------------------|
| *Injunctive - No*  | - Fashionable clothes                   | - food choices               |
|                  | - Manners of speaking                   | - name choice                |
|                  | - Gender norms for asking out           |                              |


These two types of norms are often overlapping signficantly -- injunctive rules become descriptive norms, (people strive to be normal in fear of judgment,) and then descriptive norms also become injunctive (people judge you for being abnormal.)

Morals are injunctive norms about what is right or wrong.

* Breaching Norms
Breaching: the purposeful breaking of social norms (usu. descriptive, sometimes injunctive)

E.g.: Stand in elevator facing the wrong way. Order pizza at McD's. Shake head while saying yes. Lol.

You really only learn how strong a norm is when you try to break it. We're reaallllly socially programmed to not break them.

(/Norm internalization/: people "self-sanction" for deviance) -- Panopticon -- feels like everyone is watching us, even when they're not watching us. We watch ourselves.

Norm internalization / embarrassability associated with trustworthiness, monogamy, etc.

Lots of the "sameness" we see in society actually has roots in the way they were socialized -- same initial conditions.
** Reactions to breaches
Common reactions to breaching of norms includes:

- You are sanctioned
  This is common for injunctive norms

- Gently brought in line -- people want to maintain *fluidity of interaction*
  breaching causes cognitive dissonance -- people seek to resolve it.

  "Dramaturgical analysis" (Goffman): social order like a play. People read their lines, and if someone goes "off-script," they are gently guided back on

  #+begin_quote
And all the men and women merely players;
They have their exits and their entrances;
And one man in his time plays many parts. - Shakespeare
  #+end_quote
- You are imitated
  This is (often but not always) common when the norm is privately unpopular. Can trigger a "cascade" effect...
** Cascades
Social influence is not just a stabilizing force -- can also create social change.

Cascades have fascinating properties: "early movers" disproportionately influence. Unpredictable. Can destroy a norm, or create a new one.

Random dance mob started at music festival = cascade. Emergent collective behavior

Threshold model: People have "thresholds" = number of others who must join the collective behavior before individual will.

Very sensitive to early movers: need people with 0- and low-thresholds. This makes it highly unpredictable (average threshold not necessarily telling the whole story.)
