:PROPERTIES:
:ID:       d58b0ba2-c737-43ea-b019-4787a52bd70f
:END:
#+title: a consistent worldview

drawing from: [[id:41a7d19f-ee79-4e00-b642-229caf2ed0ad][systems thinking]] / [[id:36055883-48f5-4ef5-a372-ac89cd32a80a][cybernetics]], /atomic habits/, cognitive behavioral therapy, buddhism, taoism, design thinking, etc.

being loosey-goosey for now, but i intend to try and more rigorously connect these things.

- trusting the ‘process’ / ‘system’ >>> outcomes. equanimity in the face of sometimes-fickle external outcomes is a really great quality to have.
- tight feedback loops w/ habit tracking are good — getting awareness into what’s happening and why
- what you do is who you become // by just *doing* things, we can change our sense of identity
- ‘you’ are more of a process than a static things //// change is a process, not an outcome; life is more about the journey than the destination // becoming over material having
- designing your environment is crucial to habits— bad / same-old environment triggers bad habits, while a well-designed environment can naturally promote good ones
- it’s easy to make progress on things that are clear. that makes them attractive. harder to make progress on things that are nebulous, not visually apparent to me, etc.

tension:

- habit (making things unconscious) is good for us b/c having to consciously decide every little detail would fry our brains. meditation (making things conscious) is good for us b/c suffering happens when we don’t show up to our lives.
