:PROPERTIES:
:ID:       1999996d-b676-4fc4-894b-caf82f8dd7ff
:END:
#+title: emacs

I started using Emacs in January 2020, and it has veritably changed the way I do work on my computer, and the way I think about computing in general.

* Things I really like about emacs
** Emacs enables a personal framework of [[id:1096f874-fab2-4db1-88dc-b90740bf608a][experimentation]].
It's completely hackable, which easily leads to an "experimental" mindset. I feel like people don't really try tweaking the default settings of things in important ways. Granted, you can get lost in customization, and tweaking every little aesthetic and all that...but I believe that there have been several important ways that I've been able to customize my workflow due to Emacs and the OSS that has built many different extensions for it.
* Cool configs
** [[https://gitlab.com/justinekizhak/dotfiles/blob/master/emacs/doom.d/config.org][justinekizhak]]
I like the motivation he gives for why emacs is so damn cool. "Emacs changes how you /think/ about programming." I feel like this has been very true for me. It makes many other applications seem needlessly restrictive. It feels natural to have the entire OS be an introspectable operating system.
** [[https://github.com/larstvei/dot-emacs][larstvei]]
** [[https://github.com/danielmai/.emacs.d/blob/master/config.org][danielmai]]
** [[https://tecosaur.github.io/emacs-config/config.html][tecosaur]]
** [[https://github.com/jethrokuan/dots/blob/master/.doom.d/config.el][jethro]]
* skills I am learning
** become a master of [[id:2baa1991-e3c3-4b37-8703-296cda53a9a0][debugging]] in emacs
:PROPERTIES:
:ID:       d4ae4b67-706b-4977-9299-d3667eb940ed
:END:
Something crashing? Use [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Edebug.html][Edebug]] to debug it. Something slow? You can easily [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html][profile]] it.
** lisp macros
Really powerful feature that allows one to define domain-specific syntax /within/ Emacs Lisp. Examples I really like include [[https://github.com/alphapapa/org-ql][org-ql]], [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Rx-Notation.html][rx notation]], and so many more that enable someone to write expressive, parsimonious code in a [[id:95ff3fb3-f886-41df-9f4f-5f9223b4ca4e][bottom-up]] fashion.
