#+title: goals 2023 copy

* Fix my sleep.
DEADLINE: <2023-06-01 Thu>

*Vision*: I wake up feeling refreshed and energized every day. During the night, I sleep through the night soundly. I don't feel anxious during my sleep. I feel in [[id:89f984c4-e9a3-45da-97a5-290d35191b4f][rhythm]], in a flow state.

*Plan*: Very simple, 5 components. Schedule, sunlight, exercise, avoiding light, calming.
1) Wake up at 7am. (/schedule/)
2) Join run club for exercise at 7:15am (/sunlight/, /exercise/)
3) Turn down lights, turn off screens at 10pm. (/avoiding light/)
4) Calm my mental state from 10pm-11pm. (/calming/)
5) Try to go to bed anywhere from 11pm-12am. (/schedule/)

   
*Notes on the plan*:
- For *1* and *2*, Let's leverage the social pressure of run club to make those happen.
- For *3* and *4*, I would recommend having a ritual where I am literally done with my phone past 10pm. I feel that getting late-night notifications from people, doomscrolling, etc. really drives up my cortisol levels.
- For 4, reading, journaling, etc. are all good off-screen activities. Maybe some readings would make my mind race, idk.
- Don't let social events get in the way of 5. At this point in time, fixing my sleep is more important than late-night social events.
