:PROPERTIES:
:ID:       65b7c2dd-ad4c-465f-b382-4e4d431e0be8
:END:
#+title: How I made this website

🚧 TODO 🚧 This is [[id:4bba82cd-9443-4496-8896-81323093ec11][a note I'm actively working on.]]

- [ ] [[id:b6a1ff64-eae1-4a6f-ab54-01ddfca5353d][org-mode]] description, setup
- [ ] dark mode...
- [ ] org-publish setup
- [ ] local development setup (org-publish on save, ~live-server~, etc.)
- [ ] Hovercards w/ Tippy.js
- [ ] Quotebacks
- [ ] Zotero (+ Safari extension,) ~org-cite~, ~citar~, etc.
- [ ] my advice if you want to make a system like this? [[id:e18ffcb8-f4cf-4d42-a4d7-8e88f7264f4e][Start simple and workable, and then unfold to something more complex.]]

(I guess some of this bleeds into my [[id:ad1d3f2f-a727-4e53-907b-c7215df8d35f][⚡️ emacs config]] )
  #+begin_export html
<blockquote class="quoteback" darkmode="" data-title="Quote the web with Quotebacks" data-author="@ness_labs" cite="https://nesslabs.com/quotebacks">
The ethos behind Quotebacks is one of the reasons why I love the product. Yes, it’s a great addition to my thinking toolkit, allowing me to store quotes without polluting my note-taking and thinking system. But it’s also a tool which aims at making the Internet a more generous place. If you regularly write online, give it a try!
<footer>@ness_labs<cite> <a href="https://nesslabs.com/quotebacks">https://nesslabs.com/quotebacks</a></cite></footer>
</blockquote>
<script>
  if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
    const elements = document.getElementsByClassName('quoteback');
    for (let element of elements) {
      element.setAttribute('darkmode', 'true');
    }
  }
</script>
<script note="" src="https://cdn.jsdelivr.net/gh/Blogger-Peer-Review/quotebacks@1/quoteback.js"></script>
  #+end_export
