:PROPERTIES:
:ID:       8d1e3010-0132-4bb2-a44e-fbd73a06925b
:END:
#+title: optimizing


* Optimize for clear, improvable goals
:PROPERTIES:
:ID:       f368ca02-b398-4af9-9f31-cfc0205c271f
:END:
I think that optimizing for clear, measurable metrics is a powerful [[id:00c8e647-350b-473d-bd27-8ac4836820b8][frame]]. Dan Luu talks about how one can get better at their craft in https://danluu.com/p95-skill/ -- [[id:7fd55afc-19d5-4f5c-918b-b90a2073b0f0][practice]] in an intentional way. Get feedback from others, and even from your past self by recording yourself and analyzing it.
* Optimizing for good goals
On the flip side, it's crucial to deeply consider what you're optimizing for, and why. There's been some (rightful) pushback against "optimization mindset" in Silicon Valley. I think it's kind of throwing out the baby with the bathwater to say that "optimization = bad"... that said, their core point holds water, in that lots of tech involves optimizing for objectives without any forethought about /why/ a particular objective was chosen.
