#+title: Pieces of Happy
#+roam_key: http://nickcammarata.com/writing/pieces-of-happy

http://nickcammarata.com/writing/pieces-of-happy

* Summary
:PROPERTIES:
:ID:       e9a9835e-582d-4cb3-8f5e-72ad7bdaf003
:END:

Essentially, recurring features of your environment have a compounding effect on your happiness over the course of your life. Life satisfaction research has revealed certain factors that reliably produce (and don't produce) happiness across all humans.

Also, take advantage of your personality strengths, and possibly experiment with actions that could help shore up negative personality traits (e.g. cut caffeine to lower neuroticism.)

All of this should take place within a framework of personal [[id:1096f874-fab2-4db1-88dc-b90740bf608a][experimentation]]. Try "domain randomization" on yourself -- that is, try messing with some of the parameters of your life that have been on default settings thus far. The following are sliders for some relatively meaningless parameters that probably won't affect your life that much-- because why not!

#+begin_export html
<div>
    <input type="range" id="size-slider" name="size-slider"
            min="8" max="24" value="14">
</div>
<div>
    <input type="range" id="font-slider" name="font-slider"
    min="0" max="3" value="0" step="1">
</div>
<!--TODO: make this slider turn on some d3 particle thingy-->
<div>
    <input type="range" id="violin" name="violin"
    min="0" max="100" value="30" step="10">
</div>
<script type="text/javascript">
let sizeSlider = document.getElementById("size-slider");
if (sizeSlider.addEventListener) {
    sizeSlider.addEventListener("input", function () {
        var div = document.getElementById("content");
        div.style.fontSize = sizeSlider.value + "px";
    })
}

let fontSlider = document.getElementById("font-slider");
if (fontSlider.addEventListener) {
    fontSlider.addEventListener("input", function () {
        var div = document.getElementById("content");
        var fontFamilies = {
            "0" : "Inter",
            "1" : "Georgia",
            "2" : "Courier New",
            "3" : "Brush Script MT"
        }
        div.style.fontFamily = fontFamilies[fontSlider.value]
    })
}
</script>
#+end_export

Record your findings. The cost of experimentation is small, but the potential life-changing benefits of finding something that makes you happier are immense.
* Thoughts
So...what variables of my life could I try messing with?

- Social environment -- seems to be a really big one
- What research I'm doing
- My physical room / work environment during the day
- Meditation => mindfulness.
- Changing my internet usage (takes up large chunk of my day, scrolling through algorithmic feeds)

Well, going back to the paragraph on life satisfaction:

  #+begin_quote
most of the interesting degrees of freedom that life satisfaction research tends to explore, such as *diet*, *fitness*, *drugs*, *learning*, and *mindfulness* requires little or no competition.
  #+end_quote

I'm sure there are other parameters, but for now, let's consider the set { diet, fitness, drugs, learning, and mindfulness }.

diet -> Maybe I'd feel better if I ate better. Especially at home, where I sort of just accept whatever's in the pantry.

fitness -> let's be consistent about it!

Drugs -- well...maybe strategic reintroduction of caffeine into my life could be beneficial. Earl grey tea in the morning is a pleasant experience.
Let's think about it.

Mindfulness -- for sure. It changes the experience of every moment of life -- quite the inner-loop modification. I think that intentional meditation practice every morning can verifiably change people's lives.

Learning -- having time to add content to my digital garden every day (and, like, hopefully by the time it gets rolling, I don't get so judgy about the content that's currently in it) would make me quite happy.
